default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        language_version: python3.11
        pass_filenames: false
        args:
          - --python-version=3.11
          - ingen_pydev
          - tests
        additional_dependencies:
          - pytest
          - pandas==2.2.2
          - pandas-stubs==2.2.2.240603
          - numpy==1.26.4
          - pyarrow