"""create telemetry schema

Revision ID: b5f1cf1d1d6e
Revises:
Create Date: 2026-07-22 07:01:12.538812

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5f1cf1d1d6e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("device_name", sa.String(length=128), nullable=False),
        sa.Column("product_anchor", sa.String(length=128), nullable=False),
        sa.Column("created_at_ms", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_table(
        "session",
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("source_file", sa.String(length=512), nullable=False),
        sa.Column("started_at_ms", sa.BigInteger(), nullable=False),
        sa.Column("ended_at_ms", sa.BigInteger(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("created_at_ms", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.device_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "sensor_reading",
        sa.Column("reading_id", sa.String(length=160), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("timestamp_ms", sa.BigInteger(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("lidar_distance_m", sa.Float(), nullable=False),
        sa.Column("battery_soc", sa.Float(), nullable=False),
        sa.Column("wheel_torque_fl", sa.Float(), nullable=False),
        sa.Column("wheel_torque_fr", sa.Float(), nullable=False),
        sa.Column("wheel_torque_rl", sa.Float(), nullable=False),
        sa.Column("wheel_torque_rr", sa.Float(), nullable=False),
        sa.Column("ambient_temp_c", sa.Float(), nullable=False),
        sa.Column("gps_filled", sa.Boolean(), nullable=False),
        sa.Column("gps_dropout_long", sa.Boolean(), nullable=False),
        sa.Column("lidar_saturated", sa.Boolean(), nullable=False),
        sa.Column("battery_soc_spike", sa.Boolean(), nullable=False),
        sa.Column("lidar_distance_m_spike", sa.Boolean(), nullable=False),
        sa.Column("ambient_temp_c_spike", sa.Boolean(), nullable=False),
        sa.Column("battery_soc_roll_mean_50", sa.Float(), nullable=False),
        sa.Column("battery_soc_roll_std_50", sa.Float(), nullable=False),
        sa.Column("cumulative_distance_m", sa.Float(), nullable=False),
        sa.Column("wheel_imbalance_score", sa.Float(), nullable=False),
        sa.Column("lidar_saturation_rate", sa.Float(), nullable=False),
        sa.Column("composite_health_score", sa.Float(), nullable=False),
        sa.Column("created_at_ms", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.session_id"],
        ),
        sa.PrimaryKeyConstraint("reading_id"),
        sa.UniqueConstraint(
            "device_id", "timestamp_ms", name="uq_sensor_reading_device_timestamp"
        ),
    )
    op.create_table(
        "alert",
        sa.Column("alert_id", sa.String(length=160), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("reading_id", sa.String(length=160), nullable=True),
        sa.Column("alert_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("detected_at_ms", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at_ms", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["reading_id"],
            ["sensor_reading.reading_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.session_id"],
        ),
        sa.PrimaryKeyConstraint("alert_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alert")
    op.drop_table("sensor_reading")
    op.drop_table("session")
    op.drop_table("device")
    # ### end Alembic commands ###
